import { db } from '@/db/database'
import { APP_VERSION } from '@/version'
import type { BackupFile, Category, RecordItem, AppSetting } from '@/types'
import { settingsService } from './settingsService'
const VERSION = 2
export function validateBackup(input: unknown): input is BackupFile { if (!input || typeof input !== 'object') return false; const x = input as Partial<BackupFile>; return (x.schemaVersion === 1 || x.schemaVersion === VERSION) && typeof x.appVersion === 'string' && typeof x.exportTime === 'string' && Array.isArray(x.records) && Array.isArray(x.categories) && Array.isArray(x.settings) && x.records.every(r => typeof r.amount === 'number' && typeof r.date === 'string' && (r.type === 'expense' || r.type === 'income') && typeof r.categoryId === 'number') && x.categories.every(c => typeof c.name === 'string' && (c.type === 'expense' || c.type === 'income') && (c.parentId === undefined || typeof c.parentId === 'number')) && x.settings.every(s => typeof s.key === 'string' && typeof s.value === 'string') }
export const backupService = {
  async make(): Promise<BackupFile> { return { schemaVersion: VERSION, appVersion: APP_VERSION, exportTime: new Date().toISOString(), records: await db.records.toArray(), categories: await db.categories.toArray(), settings: await db.settings.toArray() } },
  async download() { const content = await this.make(); const url = URL.createObjectURL(new Blob([JSON.stringify(content, null, 2)], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = `money-backup-${content.exportTime.slice(0, 10)}.json`; a.click(); URL.revokeObjectURL(url); await settingsService.set('lastBackupTime', String(Date.now())) },
  async restore(data: BackupFile) { if (!validateBackup(data)) throw new Error('备份文件格式无效或版本不兼容'); await db.transaction('rw', db.records, db.categories, db.settings, db.dailyExpenses, async () => { const dailyTotals = new Map<string, number>(); data.records.filter(record => record.type === 'expense').forEach(record => dailyTotals.set(record.date, (dailyTotals.get(record.date) ?? 0) + record.amount)); await Promise.all([db.records.clear(), db.categories.clear(), db.settings.clear(), db.dailyExpenses.clear()]); await db.categories.bulkAdd(data.categories as Category[]); await db.records.bulkAdd(data.records as RecordItem[]); await db.dailyExpenses.bulkPut([...dailyTotals].map(([date, amount]) => ({ date, amount }))); await db.settings.bulkPut(data.settings as AppSetting[]) }) }
}
